config/routes.rb
# frozen_string_literal: true

include RailsPlus::Helpers::Routes

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount PgHero::Engine           , at: '/pghero'
    mount RailsPerformance::Engine , at: '/rails/performance' , as: 'rails_performance'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/opinions', to: 'redirects#reviews'

  scope module: :web do
    get '/courses/free' , to: redirect('/courses?paid=0')
    get '/courses/paid' , to: redirect('/courses?paid=1')
    get '/free'         , to: redirect('/courses?paid=0')
    get '/paid'         , to: redirect('/courses?paid=1')

    resources :courses do
      resources :comments, only: %i(create update destroy)
      put :approve, on: :member
    end

    get 'user/:id', to: 'users#show', as: :user

    namespace :public, path: '' do
      resources :reviews, only: %i(index)
    end

    root to: 'welcome#index'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  include WithFrameContainerTag
  include WithMobileViews
  include WithSeo

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_for_mobile
  before_action :use_container, only: %i(index new create show edit update mini)

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  helper_method :mimic_user

  private

  def mimic_user
    return if current_user.blank?
    return current_user unless ::Pundit.policy(current_user, ::MimicUser).index?
    return nil if params[:mimic_user_id] == 'guest'
    User.find_by(id: params[:mimic_user_id].to_i).presence || current_user
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(username email password password_confirmation remember_me))
    devise_parameter_sanitizer.permit(:sign_in, keys: %i(login username email password remember_me))
    devise_parameter_sanitizer.permit(:account_update, keys: %i(username email password password_confirmation current_password))
  end

  def user_not_authorized
    flash[:alert] = 'У вас недостаточно прав для выполнения этого действия.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/devisery/application_controller.rb
# frozen_string_literal: true

module Devisery
  class ApplicationController < ::ApplicationController
    layout 'devise'
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

module Web
  class ApplicationController < ::ApplicationController
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Heroicon::Engine.helpers
  include Pagy::Frontend
  include RailsPlus::Helpers::Benchmark
  include RailsPlus::Helpers::Dashed
  include RailsPlus::Helpers::FrameContainerTag
  include RailsPlus::Helpers::GravatarURL
  include RailsPlus::Helpers::Hicon
  include RailsPlus::Helpers::RescuedCsrfMetaTags
  include RailsPlus::Helpers::RichFormFor
  include RailsPlus::Helpers::Seo

  def comments_amount
    Comment.count
  end

  def language_flag(language)
    case language
    when 'English'
      content_tag(:span, '', class: 'flag-icon flag-icon-us', title: language)
    when 'Русский'
      content_tag(:span, '', class: 'flag-icon flag-icon-ru', title: language)
    end
  end

  def course_status(course)
    course.paid? ? 'Платный' : 'Бесплатный'
  end

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end
end

app/views/application/_body.slim
.flash-collection id='flashes'
  = render 'flashes'
div id='js-permanent' data-turbolinks-permanent=''
  = render 'body_scripts'

app/views/application/_body_scripts.slim
= render 'body_scripts_webfonts', fonts: 'family=Inter:wght@300..900&family=Lora:wght@300..900'
= render 'metrics'

app/views/application/_body_scripts_webfonts.slim
/ 1. Preemptively warm up the fonts’ origin.
/
/ 2. Initiate a high-priority, asynchronous fetch for the CSS file. Works in
/    most modern browsers.
/
/ 3. Initiate a low-priority, asynchronous fetch that gets applied to the page
/    only after it’s arrived. Works in all browsers with JavaScript enabled.
/
/ 4. In the unlikely event that a visitor has intentionally disabled
/    JavaScript, fall back to the original method. The good news is that,
/    although this is a render-blocking request, it can still make use of the
/    preconnect which makes it marginally faster than the default.

link rel="preconnect" crossorigin=true href="https://fonts.gstatic.com"
link rel="preload" as="style" href="https://fonts.googleapis.com/css2?#{fonts}&display=swap"
link rel="stylesheet" media="print" onload="this.media='all'" href="https://fonts.googleapis.com/css2?#{fonts}&display=swap"
noscript: link rel="stylesheet" href="https://fonts.googleapis.com/css2?#{fonts}&display=swap"

app/views/application/_dropdown_guest.slim
= link_to new_user_session_path, class: 'button ios-button'
  .ios-button__icon = hicon 'login', class: 'w-7 block'
  .ios-button__label = t('devise.shared.links.sign_in')

app/views/application/_dropdown_user.slim
div
  = link_to 'javascript:;',
            class: 'button ios-button with-tooltip',
            data: { template: 'user_menu', tippy_interactive: true, tippy_theme: 'light', tippy_maxWidth: 300 }
    .ios-button__icon = hicon 'user', class: 'w-7 block'
    .ios-button__label Профиль
  .hidden id='user_menu' style='min-width: 200px;'
    .p-2
      = link_to 'Настройки', edit_user_registration_path,
                class: 'block p-2 rounded text-blue-600 no-underline hover:bg-blue-200 hover:text-gray-700'
      = link_to 'Выход', destroy_user_session_path, data: { method: :delete },
                class: 'block p-2 rounded text-blue-600 no-underline hover:bg-blue-200 hover:text-gray-700'

app/views/application/_favicons.html.erb
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />

app/views/application/_flash_messages.slim
.alerts
  - flash.each do |type, message|
    .alert.fade.in class=alert_class_for(type)
      button.close data-dismiss='alert' ×
      = message.try(:join, '<br>')

app/views/application/_flashes.slim
- flash.each do |type, message|
  .flash-item class="flash-item_#{type}"
    .flash-item__body class="flash-item__body_#{type}"
      .flash-item__close
      = message

app/views/application/_footer.slim
footer
  = frame_container_tag
    .text-center
      | Сделали
      =<> link_to 'Gambala', 'https://gambala.pro', target: '_blank', rel: 'noopener', class: 'no-underline text-yellow-400 hover:text-yellow-400'
      | и
      =<> link_to 'Фрей', 'https://frey.su', target: '_blank', rel: 'noopener', class: 'no-underline text-yellow-400 hover:text-yellow-400'
      br
      | 2016..2021

app/views/application/_head.slim
meta charset='utf-8'
meta name='yandex-verification' content='60e837389817f594'
meta name='viewport' content='width=device-width, initial-scale=1'
= meta_for_description
= meta_for_site_name
= meta_for_title
= meta_for_url
= title_tag
= rescued_csrf_meta_tags
= csp_meta_tag
= render 'favicons'
= stylesheet_link_tag 'web/application', media: 'all', data: { turbolinks_track: 'reload' }
= stylesheet_link_tag 'postcss', media: 'all', data: { turbolinks_track: 'reload' }
= stylesheet_link_tag 'application', media: 'all', data: { turbolinks_track: 'reload' }
= javascript_include_tag 'web/application', async: true, data: { turbolinks_track: 'reload' }
= javascript_include_tag 'application', async: true, data: { turbolinks_track: 'reload' }

app/views/application/_metrics.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter35716415 = new Ya.Metrika({
                    id:35716415,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/35716415" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/application/_nav_list.slim
.flex.flex-wrap
  .m-2
    = link_to 'Курсы', courses_path,
              class: 'block p-2 rounded font-mono text-yellow-400 hover:bg-gray-800 no-underline hover:text-yellow-400 with-tooltip',
              data: { template: 'courses_menu', tippy_interactive: true, tippy_theme: 'light', tippy_maxWidth: 300 }
    .hidden id='courses_menu' style='min-width: 200px;'
      .p-2
        = link_to 'Платные', courses_path(paid: '1'),
                  class: 'block p-2 rounded text-blue-600 no-underline hover:bg-blue-200 hover:text-gray-700'
        = link_to 'Бесплатные', courses_path(paid: '0'),
                  class: 'block p-2 rounded text-blue-600 no-underline hover:bg-blue-200 hover:text-gray-700'
        hr.my-2
        = link_to 'Добавить', new_course_path,
                  class: 'block p-2 rounded text-blue-600 no-underline hover:bg-blue-200 hover:text-gray-700'

  = link_to 'Отзывы', [:public, :reviews], class: 'm-2 p-2 rounded font-mono text-yellow-400 hover:bg-gray-800 no-underline hover:text-yellow-400'

app/views/application/_navbar.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button { class = 'navbar-toggle collapsed'
               type = 'button'
               data-toggle = 'collapse'
               data-target = '#navbar-collapse'
               aria-expanded = 'false'
             }
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Ruby Courses', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse id='navbar-collapse'
      ul.nav.navbar-nav
        li = link_to 'Все курсы', courses_path
        li = link_to 'Платные курсы', courses_path(paid: '1')
        li = link_to 'Бесплатные курсы', courses_path(paid: '0')
        li
          = link_to new_course_path do
            span Добавить курс
            span { class = 'badge'
                   data-toggle = 'tooltip'
                   data-placement = 'bottom'
                   title = 'Количество курсов на рассмотрении'
                 }
              = unapproved_courses_amount
        li = link_to 'Последние отзывы', comments_path
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown'
              i.glyphicon.glyphicon-th-large
              span.caret
            ul.dropdown-menu role='menu'
              li = link_to 'Настройки', edit_user_registration_path
              li = link_to 'Выход', destroy_user_session_path, data: { method: :delete }
        - else
          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown'
              i.glyphicon.glyphicon-lock
              span.caret
            ul.dropdown-menu role='menu'
              li = link_to 'Вход', new_user_session_path
              li = link_to 'Регистрация', new_user_registration_path

app/views/application/_soda_header.slim
.soda-header.dn_print
  .frame
    .soda-header__row
      .flex.-m-2.my-1.items-center
        = link_to root_path, class: 'flex text-lg font-semibold text-red-600 rounded my-2 p-2 no-underline hover:bg-gray-800 hover:text-red-600'
          = image_tag '/static-assets/icon-ruby.svg', class: 'w-full mr-2', style: 'max-width: 32px;'
          | Ruby.show

        = render 'nav_list'

      .flex.flex-wrap.-m-4.my-1.items-baseline
        = render 'dropdown_user'  if  mimic_user.present?
        = render 'dropdown_guest' if !mimic_user.present?